name: .NET Continous Integration

on:
  push:
    branches: [ main ]
env:
  SOLUTION_PATH: application/Apollon.Mud

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.SOLUTION_PATH}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.SOLUTION_PATH}}
    - name: Test
      run: dotnet test --no-build --verbosity normal --settings CodeCoverage.runsettings --collect:"XPlat Code Coverage" -r ./Codecoverage
      working-directory: ${{env.SOLUTION_PATH}}
    - name: Codecov
      uses: codecov/codecov-action@v1.4.1
      with:
        directory: ${{env.SOLUTION_PATH}}/Codecoverage
