name: Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install Modules
      run: npm install
      working-directory: /home/github/actions-runner/deploy/Projekt-Apollon/Projekt-Apollon/website
    - name: Build Website Content
      run: npm run-script build
      working-directory: /home/github/actions-runner/deploy/Projekt-Apollon/Projekt-Apollon/website
    - name: Delete old Website Content
      run: rm -r /var/www/html/*
    - name: Copy Website Content to root
      run: cp -r * /var/www/html
      working-directory: /home/github/actions-runner/deploy/Projekt-Apollon/Projekt-Apollon/website/build
