name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Move Website Content to root
      run: mv - r website/build/* /var/www/html
      working-directory: /home/github/actions-runner/deploy/Projekt-Apollon
